INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Starters For Vegetarian',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Soup (Vegetarian)',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Vegetarian Gravy',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Chopsuey/Chowmein',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Paneer Gravy',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Mushroom Gravy',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Vegetarian Noodles',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Rice',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Starters For Non Vegetarians',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Soups',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Gravy',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Seafood Gravy',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Noodles',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Rice (Non Veg)',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Choupsuey/Chowmien (Non Veg)',0,1);




INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Spring Roll',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Bhel',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Fingers',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Lollypop',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Crispy',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg 65',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer 65',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom 65',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Satay',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special',1,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Tomato Soup',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Clear Soup',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Noodle Soup',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Sweet Corn Soup',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Talumein Soup',1,175,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Lung Fung Soup',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchow Soup',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hot&Sour Soup',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Royal Soup',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cocktail Soup',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Gravy',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chilly Gravy',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Manchurian Gravy',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Schzwan Gravy',1,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Ginger Gravy',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Garlic Gravy',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Hong Kong Gravy',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Singapore Gravy',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Lung Fung Gravy',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Sweet & Sour Gravy',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Capsicum Gravy',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chowmein',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Szechwan Chowmein',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg American Choupsuey',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Special Choupsuey',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chinese Choupsuey',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Szechwan Choupsuey',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Special Gravy',1,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Chilly',1,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Manchurian',1,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Garlic',1,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Ginger',1,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Sweet &Sour',1,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Lung Fung',1,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Szechwan',1,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Hong Kong',1,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Singapore',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Capsicum',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Special Gravy',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Chilly',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Garlic',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Ginger',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Sweet & Sour',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Lung Fung',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Hong Kong',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Singapore',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Capsicum',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Noodles',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Conbination Rice',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hakka Noodles',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Ginger Noodles',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan Noodles',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Noodles',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Noodles',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Noodles',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Noodles',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Noodles',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchurian Noodles',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chopstick Special Rice',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Manchurian Rice',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Fried Rice',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Hong Kong Rice',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Singapore Rice',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Ginger Rice',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Szechwan Rice',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan Rice',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Rice',1,185,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Fried Rice',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Ginger Rice',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Hong Kong Rice',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Singapore Rice',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Triple Rice',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Choper Rice',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Satay',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Fui',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Fui',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Spring Roll',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mix Spring Roll',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lollypop',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Apple Chicken',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Chinese Bhel',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Crispy',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Finger',0,195,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken 65',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns 65',0,250,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Crunchy',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hunan Chicken',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Clear Soup',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Noodles Soup',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Sweet Corn Soup',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Noodles Soup',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Sweet Corn Soup',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken lung Fung Soup',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Hot & Sour Soup',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Manchow Soup',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Royal Soup',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Hong Kong Soup',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Talumein Soup',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cocktail Soup',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Manchurian Chilly CHI',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Gravy CHI',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Ginger/Garlic CHI',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Chilly Szchwan CHI',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Capsicum CHI',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken In Hot Garlic Sauce CHI',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Szechwan/Hong Kong CHI',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lung Fung Gravy CHI',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Manchurian Chilly PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Gravy PRA',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Ginger/Garlic PRA',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Chilly Szchwan PRA',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Capsicum PRA',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken In Hot Garlic Sauce PRA',0,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Szechwan/Hong Kong PRA',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lung Fung Gravy PRA',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Chilly Manchurian',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Gravy',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Ginger/Garlic',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Sweet& Sour Soup',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Chilly Szechwan',0,195,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Capsicum',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Hot In Garlic Sauce',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Szechwan/ Hong Kong',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Lung Fung',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Noodles CHI',0,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Soup CHI',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Rice CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hakka Noodles CHI',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Hakka Noodles CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Noodles CHI',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Singapore Noodles CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Noodles CHI',0,195,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Noodles CHI',0,195,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Szechwan Noodles CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Combination Rice CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchurian Noodles CHI',0,195,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Manchurian Noodles CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan Noodles CHI',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Noodles CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Soup PRA',0,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hakka Noodles PRA',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Noodles PRA',0,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Noodles PRA',0,215,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Noodles PRA',0,215,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchurian Noodles PRA',0,215,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan Noodles PRA',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Noodles PRA',0,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fried Rice CHI',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Rice CHI',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Rice CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Fried Rice CHI',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Fried Rice CHI',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Mixed Fried Rice CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Fried Rice CHI',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Mixed Rice CHI',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Ginger Fried Rice CHI',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Fried Rice CHI',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Mixed Rice CHI',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Szechwan Rice CHI',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchurian Rice CHI',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Manchurian Rice CHI',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Manchurian Rice CHI',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Triple Rice CHI',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Triple Rice CHI',0,195,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Rice CHI',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Choper Rice CHI',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed choper Rice CHI',0,250,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fried Rice PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Rice PRA',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Fried Rice PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Fried Rice PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Mixed Rice PRA',0,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Ginger Fried Rice PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Fried Rice PRA',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Mixed Rice PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchurian Rice PRA',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Manchurian Rice PRA',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Triple Rice PRA',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Triple Rice PRA',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Rice PRA',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Choper Rice PRA',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chowmien CHI',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Chowmien CHI',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('American Chopsuey CHI',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chinese Chopsuey CHI',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed American Chopsuey CHI',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Chinese Chopsuey CHI',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Special American Chopsuey CHI',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Special Chinese Chopsuey CHI',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chowmien PRA',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Chowmien PRA',0,195,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('American Chopsuey PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chinese Chopsuey PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed American Chopsuey PRA',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Chinese Chopsuey PRA',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Special American Chopsuey PRA',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Special Chinese Chopsuey PRA',0,190,1);



INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,309,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,310,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,311,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,312,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,313,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,314,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,315,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,316,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,317,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,318,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,319,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,320,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,321,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,322,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,323,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,324,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,325,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,326,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,327,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,328,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,329,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,330,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,331,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,332,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,333,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,334,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,335,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,336,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,337,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,338,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,339,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,340,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,341,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,342,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,343,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,344,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,345,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,346,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,347,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,348,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,349,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,350,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,351,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,352,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,353,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,354,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,355,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,356,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,357,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,358,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,359,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,360,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,361,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,362,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,363,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,364,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,365,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,366,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,367,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,368,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,369,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,370,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,371,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,372,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,373,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,374,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,375,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,376,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,377,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,378,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,379,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,380,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,381,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,382,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,383,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,384,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,385,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,386,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,387,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,388,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,389,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,390,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,391,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,392,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,393,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,394,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,395,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,396,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,397,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,398,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,399,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,400,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,401,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,402,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,403,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,404,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,405,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,406,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,407,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,408,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,409,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,410,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,411,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,412,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,413,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,414,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,415,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,416,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,417,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,418,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,419,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,420,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,421,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,422,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,423,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,424,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,425,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,426,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,427,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,428,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,429,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,430,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,431,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,432,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,433,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,434,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,435,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,436,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,437,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,438,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,439,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,440,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,441,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,442,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,443,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,444,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,445,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,446,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,447,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,448,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,449,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,450,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,451,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,452,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,453,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,454,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,455,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,456,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,457,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,458,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,459,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,460,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,461,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,462,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,463,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,464,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,465,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,466,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,467,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,468,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,469,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,470,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,471,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,472,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,473,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,474,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,475,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,476,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,477,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,478,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,479,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,480,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,481,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,482,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,483,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,484,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,485,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,486,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,487,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,488,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,489,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,490,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,491,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,492,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,493,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,494,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,495,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,496,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,497,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,498,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,499,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,500,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,501,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,502,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,503,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,504,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,505,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,506,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,507,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,508,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,509,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,510,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,511,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,512,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,513,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,514,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,515,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,516,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,517,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,518,1);




INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Pavbhaji',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Pulav Rice',1,1);



INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Sada Pav Bhaji',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Pavbhaji',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Pav Bhaji, With Cheese On Top Of The Bhaji',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fried Pav Bhaji, With The Pav Tossed In The Bhaji',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Pav Bhaji, With Paneer Cheese In The Bhaji',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Pav Bhaji,',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Khada Pav Bhaji, With Vegetable Chunks In The Bhaji',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Jain Pav Bhaji, Without Onions And Garlic And With Plantains Instead Of Potatoes',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Kolhapuri Pav Bhaji, Using A Spice Mix Common In Kolhapur',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dryfruit Pav Bhaji With Dried Fruits In Or On The Bhaji',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pav',1,10,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Tawa Pulav',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Tawa Pulav',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Jain Tawa Pulav',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Jain Cheese Tawa Pulav',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Tawa Pulav',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Tawa Pulav.',1,140,1);


INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,538,1);


UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='519' WHERE `main_sub_menu_map_id`='519';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='520' WHERE `main_sub_menu_map_id`='520';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='521' WHERE `main_sub_menu_map_id`='521';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='522' WHERE `main_sub_menu_map_id`='522';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='523' WHERE `main_sub_menu_map_id`='523';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='524' WHERE `main_sub_menu_map_id`='524';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='525' WHERE `main_sub_menu_map_id`='525';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='526' WHERE `main_sub_menu_map_id`='526';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='527' WHERE `main_sub_menu_map_id`='527';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='528' WHERE `main_sub_menu_map_id`='528';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='529' WHERE `main_sub_menu_map_id`='529';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='530' WHERE `main_sub_menu_map_id`='530';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='531' WHERE `main_sub_menu_map_id`='531';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='532' WHERE `main_sub_menu_map_id`='532';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='533' WHERE `main_sub_menu_map_id`='533';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='534' WHERE `main_sub_menu_map_id`='534';
UPDATE `two_pm`.`main_sub_menu_map` SET `sub_menu_id`='535' WHERE `main_sub_menu_map_id`='535';


INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Chat',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Sandwich (veg)',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Sandwich (non veg)',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Juices',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Mocktails',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Tea',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Ice Tea',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Snacks',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Cold Drinks',1,1);


UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='33' WHERE `main_menu_id`='34';
UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='34' WHERE `main_menu_id`='35';
UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='35' WHERE `main_menu_id`='36';
UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='36' WHERE `main_menu_id`='37';
UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='37' WHERE `main_menu_id`='38';
UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='38' WHERE `main_menu_id`='39';
UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='39' WHERE `main_menu_id`='40';
UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='40' WHERE `main_menu_id`='41';
UPDATE `two_pm`.`main_menu_master` SET `main_menu_id`='41' WHERE `main_menu_id`='42';



INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Samosa Chat',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Chat',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Shevpuri',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bhel Puri',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Channa Chat',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Sandwich',1,40,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Mc Grill Sandwich',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Club Sandwich',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Club Grill Sandwich',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chutney Sandwich',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Jungle Sandwich',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Jungle Club Sandwich',1,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Cheese Sandwich',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chef Special Sandwich',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Busetta Sandwich',1,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chi Grill Sandwich',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chi Club Sandwich',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chi Club Sandwich',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chi Club Grill Sandwich',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chi Roasted Sandwich',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Jungle Sandwich',1,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2PM Special Jungle Club Sandwich',1,250,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butsetta Sandwich',1,280,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Orange ',1,85,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mango',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pine Apple',1,75,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pomogranate',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Sweet Lime',1,55,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Lemon',1,45,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cocktail',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fresh Lime Soda',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Litchi Soda',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Stawberry Soda',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mango Ice Soda',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mango Panna Soda',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mojito Mint Soda',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Black Current Soda',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Blue Sky',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Tea Normal',1,15,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Masala Tea',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Plain Milk',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hot Milk',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Coffee',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Lemon',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Stawberry ',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Peach',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Plain Bread (4 Pcs)',1,10,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bread Butter (4 Pcs)',1,20,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Toast Bread (4Pcs)',1,15,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Toast Bread Butter (4Pcs)',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Plain Bread (4 Pcs) ',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Toast Bread (4 Pcs) ',1,35,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mineral Water',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Soda 500Ml',1,40,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cold Drink 500Ml',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Lassi (Sweet/Salt)',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Milk',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Extra Cheese',1,20,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Extra Butter',1,20,1);






INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,536,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,537,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,539,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,540,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,541,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,542,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,543,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,544,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,545,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,546,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,547,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,548,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,549,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,550,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,551,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,552,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,553,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,554,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,555,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,556,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,557,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,558,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,559,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,560,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,561,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,562,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,563,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,564,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,565,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,566,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,567,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,568,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,569,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,570,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,571,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,572,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,573,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,574,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,575,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,576,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,577,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,578,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,579,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,580,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,581,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(40,582,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(40,583,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(40,584,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(40,585,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(40,586,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(40,587,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(41,588,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(41,589,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(41,590,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(41,591,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(41,592,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(41,593,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(41,594,1);

