delete from  `two_pm`.`order_menu_map`;
delete from `two_pm`.`main_sub_menu_map`;
delete FROM two_pm.main_menu_master;
delete FROM two_pm.sub_menu_master;

ALTER TABLE `two_pm`.`sub_menu_master` 
AUTO_INCREMENT = 1 ;

ALTER TABLE `two_pm`.`main_sub_menu_map` 
AUTO_INCREMENT = 1 ;

ALTER TABLE `two_pm`.`main_menu_master` 
AUTO_INCREMENT = 1 ;


INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('BASMATI KA KHAZANA (NON VEG)',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('BASMATI KA KHAZANA ( VEG)',1,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('BREAD SECTION',1,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('DESSERTS',1,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('EGG',0,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('INDIAN NON VEG STARTERS',0,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('MURGON K KHAZANA',0,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('NON-VEG STARTER',0,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('SABJIYON KI BAHAR',1,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('SATH SATH',1,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('SEA FOOD MAIN COURSE',0,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('TANDOOR KI BAHAR (NON VEG)',0,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('TANDOOR KI BAHAR (VEG)',1,1);
INSERT INTO `agri_tadka`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('VEG STARTER',1,1);


INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Biryani',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Biryani (b/l)',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Dum Biryani',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Handi Biryani',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Hyderabadi Biryani',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tikka Biryani',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Biryani',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Biryani',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Biryani (b/l)',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Dum Biryani',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Handi Biryani',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Hyderabadi Biryani',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Biryani',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Dum Biryani',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Handi Biryani',0,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Pulav',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Biryani',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Dum Biryani',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Handi Biryani',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Hyderabadi Biryani',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Green Peas Pulav',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Kasmiri Pulav',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Pulav',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg.tawa Pulav',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dal Khichdi',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dal Palak Khichdi',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Palak Khichdi',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Curd Rice',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Ghee Rice',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Steam Rice',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Jeera Rice',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Biryani',1,75,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Tikka Biryani',1,85,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Pulav',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Roti',1,15,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Rumali Roti',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Roti',1,10,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Rumali Roti',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Paratha',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Lachedar Paratha',1,55,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Paratha',1,35,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Kheema Paratha',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Methi Paratha',1,35,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Stuffed Paratha',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paratha',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pudina Paratha',1,35,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Stuffed Paratha',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Naan',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Garlic Naan',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Naan',1,35,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Garlic Naan',1,65,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Kheema Naan',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Naan',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Kulcha',1,35,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Kulcha',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Vanilla',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Vanilla With Chocolate Sauce',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Vanilla Milkshake',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cassatta Slice',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mango',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fruit Salad',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fruit Salad With Ice Cream',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Honeymoon Special',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Triple Sunday',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Gadbad',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Sizzling Brownie',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Kesar Falooda',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Rose Falooda',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Boiled Egg',0,40,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Boiled Egg Bhurji (3 Pcs)',0,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Boiled Egg Chat (3 Pc)',0,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Bhurji',0,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Biryani',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Half Fry',0,40,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Pakoda',0,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Omlet',0,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Omlet',0,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Roll',0,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Dry Fry',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Liver oil Fry',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Pota Oil Fry',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Pota Liver Tawa Fry',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tawa Fry',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Pakoda',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Koliwada',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Ghee Roast',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tawa Roast',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Banjara Kabab',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Poha Bhujing',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Masala Fry',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Jeera',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Green Tawa',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kheema',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Novelty',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Junglee',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Palak',0,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Afghani',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Ap Special',0,300,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Masala',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Masala Fry',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kolhapuri',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Hyderabadi',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Handi',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Patiyala',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Seekh Kabab',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Matka Full',0,370,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Matka Half',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lahori',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Bashai',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Balti',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lajawab',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kadai',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Mughlai',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Green Masala',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Sukka (south Indian Style)',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tikka Masala',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Bunasha',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Mazedar',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Methi',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Do Pyaza',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Murg Masala',0,290,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kheema Masala',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Liver Masala',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Masala',0,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Masala Fry',0,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Mughlai',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Chicken',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Pora',0,280,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Himalaya',0,250,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kheema',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Khymber',0,270,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Handi',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Masala',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Masala Fry',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Sukka (south Indian Style)',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Kolhapuri',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Do Pyaza',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Kadai',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Green Masala',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Rogan Josh',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Kheema Mutter',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bhuna Gosht',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Shalimar',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Tawa',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Rara',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mutton Vindaloo',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bheja Tawa Fry',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bheja Masala Fry',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dal Gosht',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Dry Fry',0,300,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tawa Fry',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tawa Roast',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Pakoda',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Koliwada',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Banjara Tawa',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Liver oil Fry',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Pota Oil Fry',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Pota Liver Tawa Fry',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Poha Bhujing',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Masala Fry',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Jeera',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Green Tawa',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kheema',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Novelty',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Ghee Roast',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Junglee',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Palak',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Afghani',0,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Gobi',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Jeera',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Mutter',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Palak',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Paratha',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Tomato',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bheja Masala Fry',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bheja Tawa Fry',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bhendi Fry',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bhendi Masala',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Baby Corn Kadai',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Baby Corn Masala',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dum Aloo Punjabi',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chana Masala',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Masala',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Mushroom Masala',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Rara Masala',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Kofta',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Kolhapuri',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Jaypuri',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Rajasthani',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Harabhara Masala',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Diwani Handi',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Tartar',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Sabji Banjara',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Shaklace',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Galati Tawa',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Mix Sambhara',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Kadai',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Hyderabadi',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Handi',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Patiyala',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Maharaja',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Makhanwala',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Makhanwala',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Kabab Masala',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Balti',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Tawa Masala',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chilly Milly',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Anarkali',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Bhurji',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Tikka Masala',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Palak',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Kadai',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Kolhapuri',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Butter Masala',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Chatpatta Masala',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Handi',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Kofta',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Shajanee',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Tikka Masala',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Pasanda',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Tomato Bhartha',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Kheema',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dal Fry',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dal Tadka',1,75,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dal Kolhapuri',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dal Makhani',1,75,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Navratna Kurma',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Malai Kofta',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Malai Methi Mutter',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg 2pm special',1,250,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Tiranga',1,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fry Papad',1,10,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Masala Papad',1,20,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Roasted Papad',1,10,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Rumali Masala Papad',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Russian Salad',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Russian Salad',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cucumber Salad',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Green Salad',1,40,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Raita',1,55,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Boondi Raita',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pineapple Raita',1,75,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Plain Curd',1,40,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pomfret Malwani Green     (as per size)',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Malwani Green       (as per size)',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Rawas Malwani Green         (as per size)',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Surmai Malwani Green        (as per size)',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bhangda Masala',0,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bombil Chilly',0,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bombil Koliwada',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bombil Rava Fry',0,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bombil Tawa Fry',0,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bhangda Fry',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bhangda Tawa Fry',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mandeli Fry',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pomfret Tawa Fry',0,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pomfret Rava Fry',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pomfret Oil Fry',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pomfret Tandoori',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Surmai Tawa Fry',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Surmai Tandoori',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Surmai Chilly',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Surmai Manchurian',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pomfret Chilly',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fish Finger',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Rawas Tikka',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Chilly Manchurian',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Tawa Fry',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Koliwada',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Rava Fry',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Rawas Koliwada',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Tandoori',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Barbeque',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Pahadi',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Baby Surmai Tandoori',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Stuffed Pomfret',0,0,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Seafood Platter',0,1200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Achari Kabab',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Pahadi Kabab',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Seekh Kabab',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Reshmi Kabab',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Adraki Kabab',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lasooni Kabab',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Banjara Kabab',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Angara Kabab',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Aatishi Kabab',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tangadi Kabab',0,220,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Rojali Kabab',0,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Multani Kabab',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kasturi Kabab',0,240,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kalmi Kabab',0,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Gulmohar Kabab',0,20,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Cheese Kabab',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tandoori',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Haldi Tandoori',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Jeera Tandoori',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kalimiri Tandoori',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Masala Tandoori',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tukda Tandoori',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken White Tandoori',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Green Tandoori',0,300,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Tikka',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Kalimiri',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Non-veg Platter Fish',0,700,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Tandoori Lollipop',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Stuffed Wings',0,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Tikka',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Tikka',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Gobi Tikka',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Hariyali Tikka',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Tikka',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Babycorn Tikka',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Platter',1,400,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Malai Gobi',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Atishi Aloo',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Hilltop',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Malai Tikki',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pneer Pahadi Tikki',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Mumtaz',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Stuffed Mushroom',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Reshmi Tikka',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Baby Corn',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Finger Chips',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Pakoda',1,65,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Pakoda',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Pakoda',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Koliwada',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chana koliwada',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chana Garlic Oil Fry',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Hara Bhara Kabab',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dilruba Kabab',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Corn Tikki',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Tikki',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Corn Tikki',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Pudina Pakoda',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Reshmi Tikka',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Kheema Pattice',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Green Peas Butter Fry',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Boil Veg',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Koliwada',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pa Pad Roll',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Kathi Roll',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Chat',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Ball',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Kurkura',1,175,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Papad Kurkura',1,195,1);









INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,1,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,2,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,3,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,4,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,5,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,6,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,7,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,8,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,9,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,10,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,11,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,12,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,13,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,14,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,15,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(1,16,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,17,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,18,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,19,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,20,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,21,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,22,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,23,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,24,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,25,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,26,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,27,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,28,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,29,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,30,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,31,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,32,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,33,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(2,34,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,35,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,36,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,37,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,38,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,39,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,40,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,41,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,42,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,43,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,44,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,45,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,46,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,47,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,48,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,49,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,50,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,51,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,52,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,53,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,54,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(3,55,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,56,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,57,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,58,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,59,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,60,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,61,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,62,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,63,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,64,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,65,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,66,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,67,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(4,68,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,69,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,70,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,71,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,72,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,73,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,74,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,75,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,76,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,77,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(5,78,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,79,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,80,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,81,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,82,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,83,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,84,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,85,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,86,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,87,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,88,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,89,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,90,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,91,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,92,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,93,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,94,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,95,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,96,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(6,97,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,98,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,99,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,100,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,101,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,102,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,103,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,104,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,105,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,106,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,107,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,108,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,109,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,110,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,111,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,112,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,113,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,114,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,115,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,116,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,117,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,118,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,119,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,120,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,121,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,122,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,123,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,124,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,125,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,126,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,127,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,128,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,129,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,130,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,131,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,132,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,133,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,134,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,135,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,136,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,137,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,138,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,139,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,140,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,141,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,142,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,143,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,144,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,145,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,146,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,147,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,148,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(7,149,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,150,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,151,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,152,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,153,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,154,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,155,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,156,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,157,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,158,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,159,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,160,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,161,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,162,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,163,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,164,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,165,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,166,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,167,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,168,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,169,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,170,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,171,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,172,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,173,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,174,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,175,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,176,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,177,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,178,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,179,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,180,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,181,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,182,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,183,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,184,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,185,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,186,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,187,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,188,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,189,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,190,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,191,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,192,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,193,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,194,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,195,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,196,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,197,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,198,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,199,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,200,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,201,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,202,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,203,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,204,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,205,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,206,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,207,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,208,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,209,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,210,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,211,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,212,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,213,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,214,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,215,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,216,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,217,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,218,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,219,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,220,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,221,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,222,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,223,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,224,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,225,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,226,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,227,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,228,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,229,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,230,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(8,231,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,232,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,233,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,234,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,235,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,236,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,237,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,238,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,239,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,240,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,241,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,242,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,243,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(9,244,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,245,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,246,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,247,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,248,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,249,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,250,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,251,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,252,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,253,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,254,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,255,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,256,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,257,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,258,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,259,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,260,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,261,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,262,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,263,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,264,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,265,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,266,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,267,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,268,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,269,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,270,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,271,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,272,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,273,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,274,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,275,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,276,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,277,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(10,278,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,279,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,280,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,281,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,282,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,283,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,284,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,285,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,286,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,287,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,288,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,289,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,290,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,291,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,292,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,293,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,294,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,295,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,296,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,297,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,298,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,299,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,300,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,301,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,302,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,303,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,304,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,305,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,306,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(11,307,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,308,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,309,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,310,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,311,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,312,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,313,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,314,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,315,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,316,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,317,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,318,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,319,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,320,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,321,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(12,322,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,323,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,324,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,325,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,326,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,327,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,328,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,329,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,330,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,331,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,332,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,333,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,334,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,335,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,336,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,337,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,338,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,339,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,340,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,341,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,342,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,343,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,344,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,345,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,346,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(13,347,1);
