INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Starters For Vegetarian',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Soup (Vegetarian)',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Vegetarian Gravy',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Chopsuey/Chowmein',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Paneer Gravy',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Mushroom Gravy',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Vegetarian Noodles',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Starters(Non Veg)',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Soups',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Boneless Gravy  Chicken',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Gravy (Chicken With Bones)',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Seafood Gravy (Prawns/Fish)',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Noodles Chicken/Prawns',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Rice (Non Veg)',0,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Choupsuey/Chowmien (Non Veg)',0,1);



UPDATE `two_pm`.`main_menu_master` SET `menu_name`='STARTERS (VEG)' WHERE `main_menu_id`='15';


INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Spring Roll',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Bhel',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Finger',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Lollypop',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Crispy',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg 65',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer 65',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom 65',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Satay',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Tomato Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Clear Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Noodle Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Sweet Corn Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Talumein Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Lung Fung Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchow Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hot&Sour Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Royal Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cocktail Soup',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Gravy',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chilly Gravy',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Manchurian Gravy',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Szechwan Gravy',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Ginger Gravy',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Garlic Gravy',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Hong Kong Gravy',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Singapore Gravy',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Lung Fung Gravy',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Sweet &Sour Gravy',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Caspsium Gravy',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chowmein',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Szechwan Chowmein',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg American Choupsuey',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Special Choupsuey',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chinese Choupsuey',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Szechwan Choupsuey',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Special Gravy',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Chilli',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Manchurian',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Garlic',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Ginger',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Sweet &Sour',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Lung Fung',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Szechwan',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Hong Kong',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Singapore',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Capsicum',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Special Gravy',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Chilli',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Garlic',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Ginger',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Sweet &Sour',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Lung Fung',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Hong Kong',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Singapore',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Capsicum',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Noodles',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Noodles',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hakka Noodles',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Ginger Noodles',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan Noodles',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Noodles',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Noodles',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Noodles',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Noodles',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Noodles',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchurian Noodles',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chopstick Special Rice',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Manchurian Rice',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Fried Rice',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Hong Kong Rice',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Singapore Rice',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Singapore Rice',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Ginger Rice',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Szechwan Rice',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan Rice',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Rice',1,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Fried Rice',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Ginger Rice',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Hong Kong Rice',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Singapore Rice',1,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Triple Rice',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Satay',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Fui',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Fui',0,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Spring Roll',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mix Spring Roll',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lollypop',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Apple Chicken',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chinese Bhel',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Crispy',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Finger',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken 65',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns 65',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Crunchy',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hunan Chicken',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special ',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Clear Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Noodle Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Sweet Corn Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Noodles Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Sweet Corn Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lungfung Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Hot&Sour Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chichen Manchow Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Royal Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Hong Kong Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Talumein Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cocktail Soup',0,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Manchurian Chilly',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Gravy',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Ginger/Garlic',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Chilly Szechwan ',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Capsicum',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken In Hot Garlic Sauce',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Szechwan/Hong Kong',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lung Fung',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Chilly/Manchurian',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Gravy',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Ginger/Garlic',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Chilly Szechwan ',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Sweet &Sour Soup',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Chilly Szechwan ',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Capsicum',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken In Hot Garlic Sauce',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Szechwan/Hong Kong',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Lung Fung',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Chilly Manchurian',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Gravy',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Ginger/Garlic',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Sweet &Sour Gravy',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Chilly Szechwan',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Capsicum',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns In Hot Garlic Sause',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Szechwan/ Hong Kong',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Lung Fung',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Noodles',0,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Noodles',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Noodles',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hakka Noodles',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Hakka Noddles',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Noodles',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Singapore Noodles',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Noodles',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Noodles',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Szechwan Noodles',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Szechwan Noodles',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Combination Noodles',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchurian Noodles',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Manchurian Noodles',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Szechwan Noodles',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Noodles',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fried Rice',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Rice ',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Rice',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Egg Fried Rice',0,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Fried Rice',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Fried Rice',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hong Kong Mixed Fried Rice',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Fried Rice',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Singapore Mixed Rice',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Ginger Fried Rice',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Fried Rice',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Mixed Rice',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Combination Szechwan Rice',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Manchurian Rice',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Manchurian Rice',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Manchurian Rice',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Triple Rice',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Triple Rice',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Manchurian Szechwan Rice',0,160,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Fried Rice',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Hakka Rice',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Szechwan Rice',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Tripple Rice',0,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Prawns Manchurian Rice',0,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Choper Rice',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bomai Rice',0,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chowmien',0,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Szechwan Chowmien ',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('American Chopsuey',0,140,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chinese Chopsuey',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed American Chopsuey',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mixed Chinese Chopsuey',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Special American Chopsuey',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Special Chinese Chopsuey',0,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Szechwan Chopsuey',0,140,1);




INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,348,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,349,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,350,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,351,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,352,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,353,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,354,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,355,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(15,356,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,357,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,358,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,359,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,360,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,361,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,362,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,363,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,364,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,365,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,366,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(16,367,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,368,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,369,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,370,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,371,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,372,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,373,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,374,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,375,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,376,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,377,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(17,378,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,379,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,380,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,381,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,382,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,383,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(18,384,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,385,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,386,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,387,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,388,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,389,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,390,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,391,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,392,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,393,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,394,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(19,395,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,396,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,397,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,398,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,399,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,400,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,401,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,402,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,403,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,404,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,405,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(20,406,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,407,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,408,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,409,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,410,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,411,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,412,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,413,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,414,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,415,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,416,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,417,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,418,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,419,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,420,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,421,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,422,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,423,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,424,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,425,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,426,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,427,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,428,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,429,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,430,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,431,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(21,432,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,433,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,434,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,435,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,436,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,437,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,438,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,439,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,440,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,441,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,442,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,443,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,444,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,445,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(22,446,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,447,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,448,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,449,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,450,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,451,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,452,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,453,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,454,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,455,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,456,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,457,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,458,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(23,459,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,460,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,461,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,462,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,463,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,464,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,465,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,466,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(24,467,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,468,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,469,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,470,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,471,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,472,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,473,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,474,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,475,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,476,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(25,477,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,478,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,479,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,480,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,481,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,482,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,483,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,484,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,485,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(26,486,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,487,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,488,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,489,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,490,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,491,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,492,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,493,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,494,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,495,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,496,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,497,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,498,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,499,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,500,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,501,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(27,502,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,503,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,504,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,505,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,506,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,507,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,508,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,509,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,510,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,511,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,512,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,513,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,514,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,515,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,516,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,517,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,518,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,519,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,520,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,521,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,522,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,523,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,524,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,525,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,526,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,527,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(28,528,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,529,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,530,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,531,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,532,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,533,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,534,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,535,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,536,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(29,537,1);



update main_menu_master set menu_name = upper(menu_name);


INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Pavbhaji',1,1);


INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Sada Pav Bhaji',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Pavbhaji',1,90,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Pav Bhaji',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fried Pav Bhaji',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Paneer Pav Bhaji',1,130,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mushroom Pav Bhaji',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Khada Pav Bhaji',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Jain pav Bhaji',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Kolhapuri pav Bhaji',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Dryfruit Pav Bhaji',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pav',1,8,1);



INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,538,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,539,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,540,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,541,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,542,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,543,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,544,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,545,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,546,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,547,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(30,548,1);




INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Chat ',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Sandwich  (veg)',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Sandwich  (non veg)',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Juice',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Mocktail',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Tea ',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Ice tea',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Snack',1,1);
INSERT INTO `two_pm`.`main_menu_master` (`menu_name`, `is_veg`, `created_by`) VALUES('Cold drink',1,1);











INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Samosa Chat',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Aloo Chat',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Shevpuri',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bhel Puri',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Channa Chat',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Sandwich',1,40,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Mc Grill Sandwich',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Club Sandwich',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Club Grill Sandwich',1,150,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chutney Sandwich',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special  Jungly Sandwich',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special  Jungly Club Sandwich',1,200,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Cheese Sandwich',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Veg Chef Special Sandwich',1,180,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Busetta Veg',1,210,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chichen Grill Sandwich',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Club Sandwich',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Cub Sandwich',1,170,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Chicken Roasted Sandwich',1,190,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special  Jungly Sandwich',1,230,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('2Pm Special Jungly Club Sandwich',1,250,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Busetta',1,280,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Orange ',1,85,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mango',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pine Apple',1,75,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Pomogranate',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Sweet Lime',1,55,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Lemon',1,45,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cocktail',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Fresh Lime Soda',1,80,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Litchi Soda',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Stawberry Soda',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mango Ice Soda',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mango Panna Soda',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mojito Mint Soda',1,120,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Black Current Soda',1,110,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Blue Sky',1,100,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Tea Normal',1,15,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Masala Tea',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Plain Milk',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Hot Milk',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Coffee',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Lemon',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Stawberry ',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Peach',1,95,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Plain Bread (4 Pcs)',1,10,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Bread Butter (4 Pcs)',1,20,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Toast Bread (4Pcs)',1,15,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Toast Bread Butter (4Pcs)',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Plain Bread (4 Pcs) ',1,30,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cheese Toast Bread (4 Pcs) ',1,35,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Mineral Water',1,25,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Soda 500Ml',1,40,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Cold Drink 500Ml',1,60,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Lassi (Sweet/Salt)',1,70,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Butter Milk',1,50,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Extra Cheese',1,20,1);
INSERT INTO `two_pm`.`sub_menu_master` (`menu_name`, `is_veg`, `non_ac_unit_price`,`created_by`) VALUES('Extra Butter',1,20,1);



INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,549,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,550,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,551,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,552,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(31,553,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,554,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,555,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,556,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,557,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,558,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,559,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,560,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,561,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,562,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(32,563,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,564,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,565,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,566,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,567,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,568,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,569,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(33,570,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,571,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,572,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,573,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,574,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,575,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,576,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(34,577,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,578,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,579,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,580,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,581,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,582,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,583,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,584,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(35,585,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,586,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,587,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,588,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,589,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(36,590,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,591,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,592,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(37,593,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,594,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,595,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,596,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,597,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,598,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(38,599,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,600,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,601,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,602,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,603,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,604,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,605,1);
INSERT INTO `two_pm`.`main_sub_menu_map` (`main_menu_id`, `sub_menu_id`, `created_by`) VALUES(39,606,1);

